### PR TITLE
Add scales object member, because expo Assets expects it

### PR DESCRIPTION
**Pull request by raarts**
Hi, I am adding react-native-web support to Expo, this package will be used, but it needed this small modification.

### CODE REVIEW

**Comment by brentvatne** [comment]
:+1:

**Comment by psychoo118** [comment]
Sorry for late response, i will look into this request tomorrow, currently as I can see we should find something more abstract solution for this, maybe an extendable structure.

**Comment by raarts** [comment]
@psychoo118 bump

**Comment by peter-jozsa** [comment]
Sorry for really late response: since this change is related to your special needs, I think we should skip this PR. To solve your issue you could use your own image class instead of built-in AdaptiveImage by providing value for ‘imageClassPath‘.

**Pull request closed without merging**
