### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by jjd314**
Using this module in a project based on babel 7 was complaining about not finding 'babel-runtime-regenerator'.  I don't know that this PR contains the exact correct changes, but it did fix the problem in my project.

### CODE REVIEW

**Comment by peter-jozsa** [comment]
Thanks for reporting this issue and sharing a solution for it. I will look into these changes today and test if we are still backward-compatible.

**Comment by bausmeier** [comment]
Plus 1 for Babel 7 support. This loader seems like exactly what we need but doesn't work with our current codebase.

**Comment by externalshawnhong** [comment]
+1

**Comment by wong2** [comment]
@peter-jozsa please merge this

**Comment by RWOverdijk** [comment]
It sucks that the only solution to this problem is a project that has been abandoned (or at the very least neglected). Anyone in for a fork?

**Comment by peter-jozsa** [comment]
Sorry guys, unfortunately I'm not working on RN projects for a very long time. Maybe someone could continue development of this package who is an active RN user.

**Comment by peter-jozsa** [comment]
I just published 0.1.0 version of this package on NPM which uses Typescript for transpilation instead of Babel so I'm closing this PR.

**Pull request closed without merging**
